### ISSUE TITLE
make test fails with "ImportError: No module named google.appengine.ext"

### ISSUE THREAD

**Issue by bxm156** [Yelp/beans#10]
Looks like ```make test``` will fail with ```ImportError: No module named google.appengine.ext```
Seems like the google app-engine sdk stuff is typically installed outside of the virtualenv at /usr/local/google_appengine (Mac). 

I copied the files into the venv manually
```cp -fr /usr/local/google_appengine/google venv/lib/python2.7/site-packages```

**Comment by bxm156** [comment]
Yeah, lets update the docs to mention the need to add that to PYTHONPATH. It wasn't very clear about that in the google docs at 

https://cloud.google.com/appengine/docs/standard/python/download

**Comment by kentwills** [comment]
Added this to https://github.com/Yelp/beans/wiki/Getting-Started
