### ISSUE TITLE
Per-org preferenes

### ISSUE THREAD

**Issue by jfennell** [Yelp/beans#104]
Can there be a way for people (ie ML engineers) to specify they would like to prefer networking with other ML engineers?

**Comment by kentwills** [comment]
@jfennell An organization can set up interest groups in a few ways:  

1.  A subscription can be set up for those interested in ML 
    * This would show for all members of the organization and allow for those interested in ML in addition to those currently doing ML work
2.  Take option 1 and add [rules for meeting subscriptions](https://github.com/Yelp/beans/wiki/Rules-for-Meeting-Subscriptions)
    * This would show for only members of the organizations specifically doing ML work
3.  [unimplemented] Take a current subscription and add weights between users to make it more likely with those having ML interests would meet
    * While the functionality for match likelihood is built into the algorithm for both group and pair matching, there isn't currently an easy interface to add in these weights.  
    * This would be a small bit of development and would also require us to get information from users that we don't currently have

**Comment by kentwills** [comment]
I am closing this ticket and opening an internal one because this is specific to our internal instance @ Yelp and doesn't require a code change.
