### ISSUE TITLE
Remove hardcoded timezone in User Preference Form

### ISSUE THREAD

**Issue by kentwills** [Yelp/beans#22]
https://github.com/Yelp/beans/blob/83853d4ffebfa4c0cbe2a25601bafb344bc16efa/js/components/UserPreferenceForm.jsx#L11

This requires a larger change of storing the timezone in the database per user and defaulting to a timezone if a user doesn't have one.  By setting timezone per user, you can have user's across timezones participate in the meetings without being confused as to when they will participate.

**Comment by ajm188** [comment]
Looks like MomentTimezone also supports the names used by python's tz lib: http://momentjs.com/timezone/docs/#/data-formats/link-format/

**Comment by ajm188** [comment]
Oh I may have lied

I think you have to call this link function first, that is:

```javascript
moment.tz.link('America/Los_Angeles|US/Pacific');
```

So that would put us in the same boat as having a giant mapping from the moment-timezone names to the python tz names, which is not ideal

**Comment by ajm188** [comment]
On the other hand, if we did that in an initialization step, it would at least simplify things in the database layer
