### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by ajm188** [Yelp/beans#26]

**Comment by ajm188** [comment]
@tomelm I don't have admin :(

**Comment by tomelm** [comment]
Fixed! Let me know if you need to flip any switches on Travis's side.

**Comment by ajm188** [comment]
Thanks! I think I'm good

**Comment by ajm188** [comment]
I need to get google appengine imports working inside travis/tox. I'll come back to this tomorrow.

**Comment by ajm188** [comment]
@kentwills over to you ([client_secrets](https://travis-ci.org/Yelp/beans/jobs/204355611))

**Comment by ajm188** [comment]
Closed by #33
