### ISSUE TITLE
workday_test depends on client_secrets.json

### ISSUE THREAD

**Issue by ajm188** [Yelp/beans#29]
Relates to: #11 
Blocks #26

**Comment by ajm188** [comment]
Simple fix is probably to just mock `get_secret` to return an empty string? Might require some refactoring of the test, though

**Comment by ajm188** [comment]
On second thought, I'm not convinced this test is really that valuable at all. I propose we delete it.

**Comment by kentwills** [comment]
@bxm156 deletes this in his branch and I have a PR that deletes this as well.

**Comment by ajm188** [comment]
Can we push those? This is blocking my CI branch :)
