### ISSUE TITLE
Makefile has yelp dependencies

### ISSUE THREAD

**Issue by bxm156** [Yelp/beans#6]
Certain commands in the Makefile are yelp-specific. We may want to consider making things more generic in the future.

Specifically: pip-faster, venv-update, pip-custom platform

**Comment by asottile** [comment]
While these tools are things that are used at yelp, there's nothing yelp-specific about them:
- https://github.com/Yelp/venv-update
- https://github.com/asottile/pip-custom-platform

**Comment by bxm156** [comment]
Cool, good to know!
