### ISSUE TITLE
Schedule daily builds in Travis CI

### ISSUE THREAD

**Issue by adityavohra7** [Yelp/beans#63]
The Travis CI for [this PR](https://github.com/Yelp/beans/pull/62) failed because of a daylight saving time bug. Might be cool to have daily builds set up for `master` to catch these things earlier. Travis CI seems to have [some support](https://docs.travis-ci.com/user/cron-jobs) for Cron Jobs.

**Comment by ajm188** [comment]
cc @tomelm you have the power

**Comment by tomelm** [comment]
Didn't know this was a thing. I'll take a look soon!

**Comment by adityavohra7** [comment]
I think this is currently set up.
